### ISSUE TITLE
error while building binary

### ISSUE THREAD

**Issue by tehseensagar** [XZB-1248/Spark#63]
### Please make sure of the following things.

- [X] I have read the [documentation](https://github.com/XZB-1248/Spark/blob/master/README.md).
- [ ] 我已阅读 [文档](https://github.com/XZB-1248/Spark/blob/master/README.ZH.md)。
- [X] I'm sure there are no duplicate issues.
- [ ] 我确定没有提交和他人重复的issue。
- [X] I'm sure it's due to **Spark** itself and not my operational issue or something else.
- [ ] 我确定问题由**Spark**自身引起，不是我自己的操作失误或其他问题。

### Version / 版本

v0.21

### Describe the bug / 问题描述

compilation failed when building prod

go version 1.18
nodejs version 18 and also tried 20 but same following errors.

npm run build-prod # failed with following errors

`[webpack-cli] HookWebpackError: Transform failed with 2 errors:
925.chunk.99cef59.js:3044:18: ERROR: Transforming async generator functions to the configured target environment ("es2015") is not supported yet
925.chunk.99cef59.js:3050:19: ERROR: Transforming async generator functions to the configured target environment ("es2015") is not supported yet
    at makeWebpackError (/root/Spark-master/web/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /root/Spark-master/web/node_modules/webpack/lib/Compilation.js:3204:12
    at eval (eval at create (/root/Spark-master/web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:58:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
-- inner error --
Error: Transform failed with 2 errors:
925.chunk.99cef59.js:3044:18: ERROR: Transforming async generator functions to the configured target environment ("es2015") is not supported yet
925.chunk.99cef59.js:3050:19: ERROR: Transforming async generator functions to the configured target environment ("es2015") is not supported yet
    at failureErrorWithLog (/root/Spark-master/web/node_modules/esbuild/lib/main.js:1566:15)
    at /root/Spark-master/web/node_modules/esbuild/lib/main.js:805:29
    at responseCallbacks.<computed> (/root/Spark-master/web/node_modules/esbuild/lib/main.js:671:9)
    at handleIncomingPacket (/root/Spark-master/web/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/root/Spark-master/web/node_modules/esbuild/lib/main.js:647:7)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
caused by plugins in Compilation.hooks.processAssets
Error: Transform failed with 2 errors:
925.chunk.99cef59.js:3044:18: ERROR: Transforming async generator functions to the configured target environment ("es2015") is not supported yet
925.chunk.99cef59.js:3050:19: ERROR: Transforming async generator functions to the configured target environment ("es2015") is not supported yet
    at failureErrorWithLog (/root/Spark-master/web/node_modules/esbuild/lib/main.js:1566:15)
    at /root/Spark-master/web/node_modules/esbuild/lib/main.js:805:29
    at responseCallbacks.<computed> (/root/Spark-master/web/node_modules/esbuild/lib/main.js:671:9)
    at handleIncomingPacket (/root/Spark-master/web/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/root/Spark-master/web/node_modules/esbuild/lib/main.js:647:7)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
`

### Reproduction / 复现方式

compilation failed when building prod

go version 1.18
nodejs version 18 and also tried 20 but same following errors.

npm run build-prod # failed with following errors

`[webpack-cli] HookWebpackError: Transform failed with 2 errors:
925.chunk.99cef59.js:3044:18: ERROR: Transforming async generator functions to the configured target environment ("es2015") is not supported yet
925.chunk.99cef59.js:3050:19: ERROR: Transforming async generator functions to the configured target environment ("es2015") is not supported yet
    at makeWebpackError (/root/Spark-master/web/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /root/Spark-master/web/node_modules/webpack/lib/Compilation.js:3204:12
    at eval (eval at create (/root/Spark-master/web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:58:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
-- inner error --
Error: Transform failed with 2 errors:
925.chunk.99cef59.js:3044:18: ERROR: Transforming async generator functions to the configured target environment ("es2015") is not supported yet
925.chunk.99cef59.js:3050:19: ERROR: Transforming async generator functions to the configured target environment ("es2015") is not supported yet
    at failureErrorWithLog (/root/Spark-master/web/node_modules/esbuild/lib/main.js:1566:15)
    at /root/Spark-master/web/node_modules/esbuild/lib/main.js:805:29
    at responseCallbacks.<computed> (/root/Spark-master/web/node_modules/esbuild/lib/main.js:671:9)
    at handleIncomingPacket (/root/Spark-master/web/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/root/Spark-master/web/node_modules/esbuild/lib/main.js:647:7)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
caused by plugins in Compilation.hooks.processAssets
Error: Transform failed with 2 errors:
925.chunk.99cef59.js:3044:18: ERROR: Transforming async generator functions to the configured target environment ("es2015") is not supported yet
925.chunk.99cef59.js:3050:19: ERROR: Transforming async generator functions to the configured target environment ("es2015") is not supported yet
    at failureErrorWithLog (/root/Spark-master/web/node_modules/esbuild/lib/main.js:1566:15)
    at /root/Spark-master/web/node_modules/esbuild/lib/main.js:805:29
    at responseCallbacks.<computed> (/root/Spark-master/web/node_modules/esbuild/lib/main.js:671:9)
    at handleIncomingPacket (/root/Spark-master/web/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/root/Spark-master/web/node_modules/esbuild/lib/main.js:647:7)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
`

### Logs / 日志

```shell
compilation failed when building prod

go version 1.18
nodejs version 18 and also tried 20 but same following errors.

npm run build-prod # failed with following errors

`[webpack-cli] HookWebpackError: Transform failed with 2 errors:
925.chunk.99cef59.js:3044:18: ERROR: Transforming async generator functions to the configured target environment ("es2015") is not supported yet
925.chunk.99cef59.js:3050:19: ERROR: Transforming async generator functions to the configured target environment ("es2015") is not supported yet
    at makeWebpackError (/root/Spark-master/web/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /root/Spark-master/web/node_modules/webpack/lib/Compilation.js:3204:12
    at eval (eval at create (/root/Spark-master/web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:58:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
-- inner error --
Error: Transform failed with 2 errors:
925.chunk.99cef59.js:3044:18: ERROR: Transforming async generator functions to the configured target environment ("es2015") is not supported yet
925.chunk.99cef59.js:3050:19: ERROR: Transforming async generator functions to the configured target environment ("es2015") is not supported yet
    at failureErrorWithLog (/root/Spark-master/web/node_modules/esbuild/lib/main.js:1566:15)
    at /root/Spark-master/web/node_modules/esbuild/lib/main.js:805:29
    at responseCallbacks.<computed> (/root/Spark-master/web/node_modules/esbuild/lib/main.js:671:9)
    at handleIncomingPacket (/root/Spark-master/web/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/root/Spark-master/web/node_modules/esbuild/lib/main.js:647:7)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
caused by plugins in Compilation.hooks.processAssets
Error: Transform failed with 2 errors:
925.chunk.99cef59.js:3044:18: ERROR: Transforming async generator functions to the configured target environment ("es2015") is not supported yet
925.chunk.99cef59.js:3050:19: ERROR: Transforming async generator functions to the configured target environment ("es2015") is not supported yet
    at failureErrorWithLog (/root/Spark-master/web/node_modules/esbuild/lib/main.js:1566:15)
    at /root/Spark-master/web/node_modules/esbuild/lib/main.js:805:29
    at responseCallbacks.<computed> (/root/Spark-master/web/node_modules/esbuild/lib/main.js:671:9)
    at handleIncomingPacket (/root/Spark-master/web/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/root/Spark-master/web/node_modules/esbuild/lib/main.js:647:7)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
`
```

**Comment by tehseensagar** [comment]
issue is resolved, remove entire spark directory and redownload it . :).
